### ISSUE TITLE
Cannot connect

### ISSUE THREAD

**Issue by dinojascur** [xbezdick/amotionatrea#13]
[amotionatrea.log](https://github.com/user-attachments/files/21413840/amotionatrea.log)

Hi, after updating to 2.0.1:

1, there is prefilled url, i dont think is correct :)

<img width="338" height="386" alt="Image" src="https://github.com/user-attachments/assets/dbefffe6-a5a4-4b31-adc6-345f6f5ab964" />

2, when i change to my URL - I need to keep "ws://" structure as if I removed it, its saying invalid url. 

3, after removing an port and clicking submit... it will show:

<img width="380" height="230" alt="Image" src="https://github.com/user-attachments/assets/a74ec386-493e-4dbc-b856-3075dca7059b" />

but when i want to continue by clicking submit, nothing happens

<img width="349" height="209" alt="Image" src="https://github.com/user-attachments/assets/7a59d090-3d85-4a89-8542-3c13258a243b" />

its comming back to previous "Name" screen.

Log:

Logger: homeassistant
Source: custom_components/amotionatrea/__init__.py:208
integration: Amotion Atrea ([documentation](https://github.com/xbezdick/amotionatrea))
First occurred: 4:34:44 PM (2 occurrences)
Last logged: 4:34:44 PM

Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/config/custom_components/amotionatrea/__init__.py", line 224, in login
    await self.async_get_version()
  File "/config/custom_components/amotionatrea/__init__.py", line 208, in async_get_version
    controller_info = version_data.get('CONTROLLER', {})
                      ^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'get'

--

Logger: homeassistant
Source: custom_components/amotionatrea/__init__.py:232
integration: Amotion Atrea ([documentation](https://github.com/xbezdick/amotionatrea))
First occurred: 4:34:16 PM (4 occurrences)
Last logged: 4:34:44 PM

Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/config/custom_components/amotionatrea/__init__.py", line 220, in login
    await self.ui_scheme()
  File "/config/custom_components/amotionatrea/__init__.py", line 232, in ui_scheme
    self._max_flow = self.control_scheme["types"]["flow_ventilation_req"]["max"]
                     ~~~~~~~~~~~~~~~~~~~^^^^^^^^^
TypeError: string indices must be integers, not 'str'

---

Source: custom_components/amotionatrea/__init__.py:231
integration: Amotion Atrea ([documentation](https://github.com/xbezdick/amotionatrea))
First occurred: 4:34:34 PM (3 occurrences)
Last logged: 4:34:43 PM

Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/config/custom_components/amotionatrea/__init__.py", line 220, in login
    await self.ui_scheme()
  File "/config/custom_components/amotionatrea/__init__.py", line 231, in ui_scheme
    if "flow_ventilation_req" in message["requests"]:
                                 ~~~~~~~^^^^^^^^^^^^
TypeError: string indices must be integers, not 'str'


--

Logger: homeassistant
Source: custom_components/amotionatrea/__init__.py:209
integration: Amotion Atrea ([documentation](https://github.com/xbezdick/amotionatrea))
First occurred: 4:31:06 PM (14 occurrences)
Last logged: 4:34:35 PM

Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/config/custom_components/amotionatrea/__init__.py", line 224, in login
    await self.async_get_version()
  File "/config/custom_components/amotionatrea/__init__.py", line 209, in async_get_version
    self.sw_version = controller_info.get('version', 'Unknown')
                      ^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'

log attached.

**Comment by xbezdick** [comment]
Grr so it clearly connects but API that I thought is universal across the units is not.

**Comment by xbezdick** [comment]
Can I get from your unit outputs of these endpoints?

http://192.168.1.100/api/version
http://192.168.1.100/api/ui_control_scheme

and http://192.168.1.100/api so we get the list of endpoints

aaaand do you have http://192.168.1.100/openapi.yaml ?

**Comment by dinojascur** [comment]
yeeeah... loooks like Atrea is making their units super-complex between the models.

So, output from   /version nad /ui_control_scheme attached.


The /api and /openapi.yaml

"This URI does not exist"

[ui_control_scheme.txt](https://github.com/user-attachments/files/21416330/ui_control_scheme.txt)

[version.txt](https://github.com/user-attachments/files/21416344/version.txt)


and btw mine is on .16 ;)

**Comment by andreiiliuta** [comment]
This is still happening to me. However it works on the fork from cataliniatan

http://192.168.1.100/api/version
{"code":"OK","error":null,"result":{"COMPACT":"Compact_M v0.5.4\r\n","CONTROLLER":null,"CONTROL_ADMIN":null,"GATEWAY":{"build":"02.06.2025","githash":"2ac2c00","version":"aMCE-v2.3.1"},"MAPPER":null,"REMOTE_API":null}}


http://192.168.1.100/api/ui_control_scheme
{"code":"OK","error":null,"result":{"components":{"cooler_a":{"component_type":"cooler","excersise_period":24,"exchanger_stop_delay":30,"hp_t_ref_max":31.0,"hp_t_ref_min":18.0,"hp_t_ref_u_max":9.7,"hp_t_ref_u_min":1.3,"i_gain":0.01,"order_index":0,"output_min":10,"p_gain":0.04,"passover_time":20,"position":"EXTERNAL","pump_delay":20,"temp_bivalence":0.0,"type":"HEATPUMP"},"heater_a":{"component_type":"heater","excersise_period":24,"exchanger_stop_delay":30,"hp_t_ref_max":31.0,"hp_t_ref_min":18.0,"hp_t_ref_u_max":9.7,"hp_t_ref_u_min":1.3,"i_gain":0.01,"order_index":0,"output_min":20,"p_gain":0.05,"passover_time":30,"position":"EXTERNAL","pump_delay":20,"static_rate":0,"temp_bivalence":-8.0,"type":"HEATPUMP"}},"config":["season_switch_temp","season_request","temp_oda_mean_interval","temp_ida_heater_hyst","temp_ida_cooler_hyst","temp_cool_active_offset"],"requests":["work_regime","fan_power_req","temp_request","bypass_control_req"],"scene_items":["work_regime","fan_power_req","temp_request","bypass_control_req","triggerFunctions"],"states":["active"],"types":{"bypass_control_req":{"type":"enum","unit":"enum","valueType":"BypassControlRequest","values":["AUTO","CLOSED","OPEN"]},"cooler_status":{"type":"bool","unit":"On","valueType":"bool"},"fan_eta_factor":{"max":100.0,"min":0.0,"step":1,"type":"range","unit":"%","valueType":"percent"},"fan_power_req":{"max":100.0,"min":0.0,"step":1,"type":"range","unit":"%","valueType":"percent"},"fan_sup_factor":{"max":100.0,"min":0.0,"step":1,"type":"range","unit":"%","valueType":"percent"},"heater_status":{"type":"bool","unit":"On","valueType":"bool"},"mode_current":{"type":"enum","unit":"enum","valueType":"DedicatedMode","values":["OFF","EVAPORATION","RUNDOWN","NORMAL","FILTER_TEST","FLOW_STABILIZATION","SUBSTITUTE_CONTROL","INTERVAL_VENTILATION","DEHUMIDIFICATION","DEFROST_HRC","FORCE_CIRCULATION","STARTUP","WARM_UP","EMERGENCY_OFF","MANUAL","ANTIFREEZE","PREVENT_OFF","SMOKE_EXTRACTION"]},"season_current":{"type":"enum","unit":"enum","valueType":"Season","values":["AUTO_TODA","AUTO_TODA_RATIO","HEATING","NON_HEATING","USER"]},"season_request":{"type":"enum","unit":"enum","valueType":"Season","values":["AUTO_TODA","AUTO_TODA_RATIO","HEATING","NON_HEATING","USER"]},"season_switch_temp":{"max":50.0,"min":-30.0,"step":0.1,"type":"range","unit":"°C","valueType":"t_outside"},"temp_cool_active_offset":{"max":3.0,"min":0.1,"step":0.1,"type":"range","unit":"°C","valueType":"t_hysterese"},"temp_eha":{"max":50.0,"min":-30.0,"step":0.1,"type":"range","unit":"°C","valueType":"t_outside"},"temp_eta":{"max":40.0,"min":10.0,"step":0.1,"type":"range","unit":"°C","valueType":"t_inside"},"temp_ida":{"max":40.0,"min":10.0,"step":0.1,"type":"range","unit":"°C","valueType":"t_inside"},"temp_ida_cooler_hyst":{"max":3.0,"min":0.1,"step":0.1,"type":"range","unit":"°C","valueType":"t_hysterese"},"temp_ida_heater_hyst":{"max":3.0,"min":0.1,"step":0.1,"type":"range","unit":"°C","valueType":"t_hysterese"},"temp_oda":{"max":50.0,"min":-30.0,"step":0.1,"type":"range","unit":"°C","valueType":"t_outside"},"temp_oda_mean":{"max":50.0,"min":-30.0,"step":0.1,"type":"range","unit":"°C","valueType":"t_outside"},"temp_oda_mean_interval":{"type":"enum","unit":"enum","valueType":"TempOdaMeanIntervalOptions","values":["HOURS_1","HOURS_3","HOURS_6","HOURS_12","DAYS_1","DAYS_2","DAYS_3","DAYS_4","DAYS_5","DAYS_6","DAYS_7","DAYS_8","DAYS_9","DAYS_10"]},"temp_request":{"max":40.0,"min":10.0,"step":0.5,"type":"range","unit":"°C","valueType":"t_control"},"temp_sup":{"max":100.0,"min":-30.0,"step":0.1,"type":"range","unit":"°C","valueType":"t_system"},"work_regime":{"type":"enum","unit":"enum","valueType":"WorkRegime","values":["OFF","AUTO","VENTILATION","NIGHT_PRECOOLING","DISBALANCE"]}},"unit":["season_current","temp_oda","temp_oda_mean","temp_eta","temp_eha","fan_sup_factor","fan_eta_factor","temp_ida","temp_sup","heater_status","cooler_status","mode_current"]}}

http://192.168.1.100/api 
http://192.168.0.180/openapi.yaml
This URI does not exist
